### PR TITLE
Use Fable.Extras for platform detection

### PR DESCRIPTION
**Pull request by jwosty**
Will fix https://github.com/jwosty/Fable.System.IO/issues/5

### CODE REVIEW

**Comment by jwosty** [comment]
yarn tests fail with the following output:

```
ReferenceError: navigator is not defined
    at s (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:73513)
    at Object.<anonymous> (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:51455)
    at n (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:110)
    at Module.<anonymous> (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:75649)
    at Module.<anonymous> (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:114909)
    at n (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:110)
    at D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:902
    at Object.<anonymous> (D:\a\Fable.System.IO\Fable.System.IO\tests\bin\mocha\bundle.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.exports.requireOrImport (D:\a\Fable.System.IO\Fable.System.IO\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (D:\a\Fable.System.IO\Fable.System.IO\node_modules\mocha\lib\esm-utils.js:33:34)
    at Mocha.loadFilesAsync (D:\a\Fable.System.IO\Fable.System.IO\node_modules\mocha\lib\mocha.js:431:19)
    at singleRun (D:\a\Fable.System.IO\Fable.System.IO\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (D:\a\Fable.System.IO\Fable.System.IO\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (D:\a\Fable.System.IO\Fable.System.IO\node_modules\mocha\lib\cli\run.js:362:11)
    at innerArgv.then.argv (D:\a\Fable.System.IO\Fable.System.IO\node_modules\yargs\lib\command.js:241:49)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

Platform detector seems to be failing (these tests run under Node+Mocha). @Schmew any idea how to fix this?

**Comment by Shmew** [comment]
Hmm, that's odd. It only makes a call to the navigator if it returns *false* on if it's a node environment. It correctly returns true in my own tests. The code is almost verbatim of the original library. Could you check what `JSe.Platform.has.gui` and `JSe.Platform.is.node` return for you in your tests?

**Comment by jwosty** [comment]
Interesting. Both output false when you run it via ``yarn test``:

```
JSe.Platform.has.gui = false
JSe.Platform.is.node = false

ReferenceError: navigator is not defined
    at c (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:53670)
    at Object.<anonymous> (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:41013)
    at n (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:110)
    at Module.<anonymous> (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:65473)
    at Module.<anonymous> (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:105007)
    at n (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:110)
    at C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:902
    at Object.<anonymous> (C:\Users\jwost\source\repos\Fable.System.IO\tests\bin\mocha\bundle.js:1:912)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.exports.requireOrImport (C:\Users\jwost\source\repos\Fable.System.IO\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (C:\Users\jwost\source\repos\Fable.System.IO\node_modules\mocha\lib\esm-utils.js:33:34)
    at Mocha.loadFilesAsync (C:\Users\jwost\source\repos\Fable.System.IO\node_modules\mocha\lib\mocha.js:431:19)
    at singleRun (C:\Users\jwost\source\repos\Fable.System.IO\node_modules\mocha\lib\cli\run-helpers.js:125:15)
    at exports.runMocha (C:\Users\jwost\source\repos\Fable.System.IO\node_modules\mocha\lib\cli\run-helpers.js:190:10)
    at Object.exports.handler (C:\Users\jwost\source\repos\Fable.System.IO\node_modules\mocha\lib\cli\run.js:362:11)
    at C:\Users\jwost\source\repos\Fable.System.IO\node_modules\yargs\lib\command.js:241:49
```

**Comment by Shmew** [comment]
Okay I'll clone the branch and look into this when I get a chance

**Comment by Shmew** [comment]
I figured out why this isn't working. It looks like when running in mocha `process.versions.node` is undefined. I can confirm it works when running the tests via Jest, so it's just the testing environment that's causing this. You can stub the functions using a compiler directive like `#if MOCHA` and add it when you run the tests or switch to using [Fable.Jester](https://github.com/Shmew/Fable.Jester).

I tried to find a way to properly detect if mocha was running but didn't find anything convincing. The thing with that route is you'd be adding code to your library to account for your testing environment which isn't great.

**Comment by jwosty** [comment]
I've worked around the issue by changing Fable.System.IO.Path to be a lazily-evaluated property (instead of a simple module variable, as it was before), so that the platform detection code doesn't get called if we don't explicitly reference the API that uses it, as in the test harness. Seems to work!

On an unrelated issue, Ubuntu CI was [suddenly having issues](https://github.com/jwosty/Fable.System.IO/runs/3343758162) building/running fable stuff correctly, so I've disabled it for now; now only the Windows CI runs the yarn tests. Not sure why this is, as it works fine for me under WSL...

Anyways, thanks for the insight, @Shmew!

**Pull request merged**
